version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_solicitud
    environment:
      POSTGRES_DB: solicitud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
